### ISSUE TITLE
The NVIDIA probe routine was not called for 1 device(s)

### ISSUE THREAD

**Issue by probonopd** [probonopd/meilix#1]
`nouveau` is still getting loaded.

```
[   89.713053] NVRM: The NVIDIA probe routine was not called for 1 device(s).
[   89.713054] NVRM: This can occur when a driver such as: 
               NVRM: nouveau, rivafb, nvidiafb or rivatv 
               NVRM: was loaded and obtained ownership of the NVIDIA device(s).
[   89.713055] NVRM: Try unloading the conflicting kernel module (and/or
               NVRM: reconfigure your kernel without the conflicting
               NVRM: driver(s)), then try loading the NVIDIA kernel module
               NVRM: again.
[   89.713055] NVRM: No NVIDIA graphics adapter probed!
```

**Comment by probonopd** [comment]
Needs `sudo /usr/sbin/update-initramfs.distrib -u`?

**Comment by Marietto2008** [comment]
hello. I get the same error. how did u fix that ?

**Comment by probonopd** [comment]
By entirely deleting Nouveau:

https://github.com/probonopd/system/blob/486f77493a73adceb298e8de987eaefe050073a2/remaster.sh#L63

**Comment by ghost** [comment]
> By entirely deleting Nouveau:
> 
> https://github.com/probonopd/system/blob/486f77493a73adceb298e8de987eaefe050073a2/remaster.sh#L63

Please don't do! Disable nouveau at boot time is more safe than delete entirely all modules file from the kernel!
Mainly for two reason, first one this solution is not persistent, at next kernel you will expirience in the same issue; second reason it is not elegant :)

All linux distribution have default files where you can set your own settings, to disable permanently nouveau and do not cause annoying errors edit the file /etc/default/grub, after the ¨quite¨ in the variable GRUB_CMDLINE_LINUX_DEFAULT= set this: rdblaclist=nouveau.

Once the file is saved regenerate the grub configuration file
update-grub2
check also nvidia installer create for you the blacklist file in:
/etc/modprobe.d and /lib/modprobe.d

then regenerate the initramfs:
update-initramfs -u

This have resolve the issue for me.

**Comment by probonopd** [comment]
Thanks @AtomiX84. Are you aware that we are creating a Live ISO here?

**Comment by erichorwath** [comment]
`rdblaclist=nouveau` didn't work for me, but `modprobe.blacklist=nouveau` after `splash` did the trick for me on [Ubuntu 23.10.1](https://hachyderm.io/@EricHorwath/111392642081507272)

**Comment by BURN-MICROSUCK** [comment]
thanks a lot nvidiot and and b*ll piece of shit g*te$ for HOURS OF FUCKING AROUND FOR THE SLIGHTEST STUPIDEST LITTLE THING

**Comment by BURN-MICROSUCK** [comment]
As always, thanks a lot nvidiot and b!ll piece of shit g#&te$ for HOURS AND HOURS OF FUCKING AROUND FOR THE SLIGHTEST STUPIDEST LITTLE THING

**Comment by BURN-MICROSUCK** [comment]
As always, thanks a lot nvidiot and b!ll piece of shit g#&te$ for their closed-source proprietary garbage malware invading GNU/Linux and HOURS AND HOURS OF FUCKING AROUND JUST TO FIX THE SLIGHTEST STUPIDEST LITTLE THING.
